var TABLENAME varchar2(20);
exec :TABLENAME := '%FIELD%'; 

-- All tables of current user
SELECT TABLE_NAME, TABLESPACE_NAME, CLUSTER_NAME, IOT_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME LIKE :TABLENAME
ORDER BY TABLESPACE_NAME, CLUSTER_NAME, IOT_NAME, TABLE_NAME;

-- All tables accessible by current user
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME LIKE '%MDATA%'
ORDER BY OWNER, TABLE_NAME;

SELECT DISTINCT TABLESPACE_NAME, CLUSTER_NAME, IOT_NAME FROM user_tables;
SELECT * FROM all_users ORDER BY USERNAME;
